/**
 * @file Community schema
 * @author Evan Jelle
 * @exports CommunitySchema the schema for the community model
 */
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *      schemas:
 *          Community:
 *              type: object
 *              required:
 *                  - name
 *                  - lat
 *                  - long
 *                  - owner_user_id
 *                  - county_id
 *              properties:
 *                  id:
 *                      type: integer
 *                      description: autogenerated id
 *                  name:
 *                      type: string
 *                      description: name of the community
 *                  lat:
 *                      type: number
 *                      format: float
 *                      description: latitude of the community
 *                  long:
 *                      type: number
 *                      format: float
 *                      description: longitude of the community
 *                  owner_user_id:
 *                      type: integer
 *                      description: id of the owning user
 *                  county_id:
 *                      type: integer
 *                      description: id of the county
 *                  createdAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was created
 *                  updatedAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was last updated
 *              example:
 *                  id: 1
 *                  name: Colony
 *                  lat: 38.0711049
 *                  long: -95.36666
 *                  owner_user_id: 1
 *                  county_id: 2
 *                  createdAt: 2025-02-4T15:36:32.000Z
 *                  updatedAt: 2025-02-4T15:36:32.000Z

 */

const CommunitySchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  lat: {
    type: Sequelize.FLOAT,
    allowNull: false,
  },
  long: {
    type: Sequelize.FLOAT,
    allowNull: false,
  },
  owner_user_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  county_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default CommunitySchema;
