/**
 * @file County schema
 * @author Evan Jelle
 * @exports CountySchema the schema for the County model
 */
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *      schemas:
 *          County:
 *              type: object
 *              required:
 *                  - name
 *                  - code
 *                  - seat
 *                  - population
 *                  - est_year
 *              properties:
 *                  id:
 *                      type: integer
 *                      description: autogenerated id
 *                  name:
 *                      type: string
 *                      description: name of the county
 *                  code:
 *                      type: string
 *                      description: two letter county code
 *                  seat:
 *                      type: string
 *                      description: county seat city
 *                  population:
 *                      type: integer
 *                      description: population of the county
 *                  est_year:
 *                      type: integer
 *                      description: year the county was established
 *                  createdAt:
 *                      type: string
 *                      format: date-time
 *                      description: when  the record was created
 *                  updatedAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was last updated
 *              example:
 *                  id: 1
 *                  name: Allen
 *                  code: AL
 *                  seat: Iola
 *                  population: 1234
 *                  est_year: 1855
 *                  createdAt: 2025-02-04T15:36:32.000Z
 *                  updatedAt: 2025-02-04T15:36:32.000Z
 */

const CountySchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  code: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  seat: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  population: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  est_year: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default CountySchema;
