/**
 * @file Document schema
 * @author Evan Jelle
 * @exports DocumentSchema the schema for the Document model
 */
import Sequelize from 'sequelize';

/**
 * @swagger
 * components:
 *      schemas:
 *          Document:
 *              type: object
 *              required:
 *                  - disaply_name
 *                  - filename
 *                  - size
 *                  - type
 *              properties:
 *                  id:
 *                      type: integer
 *                      description: autogenerated id
 *                  dispaly_name:
 *                      type: string
 *                      description: name of the document
 *                  filename:
 *                      type: string
 *                      description: filename of the document
 *                  size:
 *                      type: integer
 *                      description: size of the document in bytes
 *                  type:
 *                      type: integer
 *                      description: size of the document in bytes
 *                  createdAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was created
 *                  updatedAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was last updated
 *              example:
 *                  id: 1
 *                  display_name: Colony.jpeg
 *                  filename: sample.jpg
 *                  size: 16
 *                  type: image/jpeg
 *                  createdAt: 2025-02-4T15:36:32.000Z
 *                  updatedAt: 2025-02-4T15:36:32.000Z
 */

const DocumentSchema = {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    display_name: {
        type: Sequelize.STRING,
        allowNull: false,
    },
    filename: {
        type: Sequelize.STRING,
        allowNull: false,
    },
    size: {
        type: Sequelize.INTEGER,
        allowNull: false,
    },
    type: {
        type: Sequelize.STRING,
        allowNull: false,
    },
    createdAt: {
        type: Sequelize.DATE,
        allowNull: false,
    },
    updatedAt: {
        type: Sequelize.DATE,
        allowNull: false,
    }
}

export default DocumentSchema