/**
 * @file Metadata schema
 * @author Evan Jelle
 * @exports MetadataSchema the schema for the Metadata model
 */
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *      schemas:
 *          Metadata:
 *              type: object
 *              required:
 *                  - title
 *                  - author
 *                  - publisher
 *                  - date
 *                  - abstract
 *                  - citation
 *                  - copyright_id
 *                  - keywords
 *                  - owner_user_id
 *              properties:
 *                  id:
 *                      type: integer
 *                      description: autogenerated id
 *                  title:
 *                      type: string
 *                      description: title of the metadata record
 *                  author:
 *                      type: number
 *                      description: author of the work
 *                  publisher:
 *                      type: string
 *                      description: year of the publication
 *                  date:
 *                      type: string
 *                      description: year-motnh of publication
 *                  abstract:
 *                      type: string
 *                      description: abstract of the work
 *                  citation:
 *                      type: string
 *                      description: citation for the work
 *                  copyright_id:
 *                      type: string
 *                      format: integer
 *                      description: id of the copyright holder
 *                  keywords:
 *                      type: string
 *                      description: keywords for the work
 *                  owner_user_id:
 *                      type: integer
 *                      description: id of the owning user
 *                  createdAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was created
 *                  updatedAt:
 *                      type: string
 *                      format: date-time
 *                      description: when the record was last updated
 *              example:
 *                  id: 1
 *                  title: Riley, Riley County
 *                  author: Evan Jelle
 *                  publisher: Kansas State University
 *                  date: 2017-09
 *                  abstract: This paper shares the history and stories of those in the town.
 *                  citation: Evan Jelle, Riley County
 *                  copyright_id: 1
 *                  keywords: Riley County, Manhattan, Kansas
 *                  owner_user_id: 1
 *                  createdAt: 2025-02-04T15:36:32.000Z
 *                  updatedAt: 2025-02-04T15:36:32.000Z
 */

const MetadataSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  title: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  author: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  publisher: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  date: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  abstract: {
    type: Sequelize.TEXT,
    allowNull: false,
  },
  citation: {
    type: Sequelize.TEXT,
    allowNull: false,
  },
  copyright_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  keywords: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  owner_user_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default MetadataSchema;
